name: Rebuild Master 

on:
  schedule:
    - cron: '15 1 * * *'
  push:
    branches: 
      - master
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [10, 12, 14]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
      - name: Cache Docker layers
        uses: actions/cache@v2
        id: cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Docker login
        run: | 
          echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Run Buildx
        run: |
          if [ ${{ matrix.node_version }} -eq "12" ]; then
              export DEVEL="-t ctmagazin/ctnodered:devel"
          fi
          if [ ${{ matrix.node_version }} -eq "14" ]; then
              export PLATFORMS="linux/amd64,linux/arm64,linux/s390x "
          else
              export PLATFORMS="linux/amd64,linux/arm/v7,linux/arm64/v8,linux/arm/v6,linux/s390x "
          fi
          docker buildx build \
            --platform $PLATFORMS \
            -o type=registry \
            -t ctmagazin/ctnodered:"devel-${{ matrix.node_version }}" \
            $DEVEL \
            --build-arg NODE_VERSION=${{ matrix.node_version }} \
            --build-arg NODE_RED_VERSION=latest \
            --build-arg OS=alpine \
            --build-arg BUILD_DATE="$(date +"%Y-%m-%dT%H:%M:%SZ")" \
            --build-arg TAG_SUFFIX=devel-${{ matrix.node_version }} \
            --file ./docker-image/Dockerfile ./docker-image
